const WHITELIST_LEVEL_TEAM_AND_DEV = 'TEAM_AND_DEV'
const WHITELIST_LEVEL_ALLOWED_ONLY = 'ALLOWED_ONLY'
const WHITELIST_LEVEL_HOLDERS_ALL = 'HOLDERS_ALL'
const WHITELIST_LEVELS = [
  WHITELIST_LEVEL_TEAM_AND_DEV,
  WHITELIST_LEVEL_ALLOWED_ONLY,
  WHITELIST_LEVEL_HOLDERS_ALL
]

module.exports = {
  WHITELIST_LEVEL_TEAM_AND_DEV,
  WHITELIST_LEVEL_ALLOWED_ONLY,
  WHITELIST_LEVEL_HOLDERS_ALL,
  WHITELIST_LEVELS
}